import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Bill } from '@/types';

/**
 * Generates and downloads a clean, printable PDF statement report for pending bills.
 * This is client-side only and runs directly in the user's browser.
 */
export function generatePendingBillsPDF(placeName: string, bills: Bill[]) {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Elegant HSL tailoring (Green-600 / Amber-700 / Gray-800)
    const primaryColor: [number, number, number] = [22, 163, 74]; // Tailwind Green-600
    const textColor: [number, number, number] = [31, 41, 55]; // Gray-800
    const borderColor: [number, number, number] = [229, 231, 235]; // Gray-200

    // Top Brand Space / Business Banner
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text('GANESH PRINTERS', 14, 16);

    // Business Sub-banner/Details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128); // Gray-500
    doc.text('D.T.P | OFFSET | WALL POSTER | ALL TYPE OF MULTI-COLOUR PRINTING WORKS', 14, 25);
    doc.text('CONTACT: 94430 68755', 14, 31);

    // Horizontal Divider Rule
    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.5);
    doc.line(14, 36, 196, 36);

    // Statement Metadata (Left-aligned)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text('PENDING BILLS REPORT', 14, 46);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(`PLACE: ${placeName.toUpperCase()}`, 14, 52);

    // Date & Timing info (Right-aligned)
    const now = new Date();
    const exportDateStr = now.toLocaleDateString('en-IN', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    });
    const exportTimeStr = now.toLocaleTimeString('en-IN', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text(`Created Date: ${exportDateStr}`, 130, 46);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated at: ${exportTimeStr}`, 130, 51);

    // Dynamic sum calculation
    const totalPendingSum = bills.reduce((sum, b) => sum + Number(b.amount), 0);

    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL PENDING:', 130, 57);
    doc.setTextColor(194, 65, 12); // Amber-700
    // Format Indian Rupees system with lakhs/crores commas, using Rs. prefix to prevent character map corruption
    const formattedSum = 'Rs. ' + new Intl.NumberFormat('en-IN', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(totalPendingSum);

    doc.text(formattedSum, 130, 62);

    // Table Data Mapping
    const tableRows = bills.map((bill, index) => {
      const createdDate = new Date(bill.created_at).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric'
      });
      const dueDate = bill.due_date
        ? new Date(bill.due_date).toLocaleDateString('en-IN', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric'
        })
        : '-';

      const formattedAmount = 'Rs. ' + new Intl.NumberFormat('en-IN', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      }).format(Number(bill.amount));

      return [
        bill.bill_number,
        formattedAmount,
        createdDate,
        dueDate
      ];
    });

    // Render Table using AutoTable
    autoTable(doc, {
      startY: 70,
      head: [['Bill No.', 'Amount (Rs.)', 'Created Date', 'Due Date']],
      body: tableRows,
      headStyles: {
        fillColor: primaryColor,
        textColor: [255, 255, 255],
        fontSize: 10,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 9,
        textColor: textColor,
      },
      columnStyles: {
        0: { halign: 'left' },
        1: { halign: 'left' }, // Changed from 'right' to 'left' to align the Amount column
        2: { halign: 'left' },
        3: { halign: 'left' },
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251], // Gray-50
      },
      margin: { left: 14, right: 14 },
    });

    // Footer spacing & rendering
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175); // Gray-400
      doc.text(
        'Generated by Delivery Billing App — Ganesh Printers',
        14,
        doc.internal.pageSize.height - 10
      );
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width - 25,
        doc.internal.pageSize.height - 10
      );
    }

    // Auto-download attachment
    const safePlaceName = placeName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    doc.save(`pending_bills_${safePlaceName}_${exportDateStr.replace(/\//g, '-')}.pdf`);
    return true;
  } catch (err) {
    console.error('PDF Statement generation failure:', err);
    return false;
  }
}